# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scraper.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1161, 884)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Info = QtWidgets.QLabel(Dialog)
        self.Info.setMinimumSize(QtCore.QSize(0, 27))
        self.Info.setText("")
        self.Info.setObjectName("Info")
        self.gridLayout_2.addWidget(self.Info, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fetch = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetch.sizePolicy().hasHeightForWidth())
        self.fetch.setSizePolicy(sizePolicy)
        self.fetch.setObjectName("fetch")
        self.gridLayout.addWidget(self.fetch, 0, 1, 1, 1)
        self.URL = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.URL.sizePolicy().hasHeightForWidth())
        self.URL.setSizePolicy(sizePolicy)
        self.URL.setMinimumSize(QtCore.QSize(300, 0))
        self.URL.setObjectName("URL")
        self.gridLayout.addWidget(self.URL, 0, 0, 1, 1)
        self.ctrl_frame = QtWidgets.QFrame(Dialog)
        self.ctrl_frame.setEnabled(True)
        self.ctrl_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctrl_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctrl_frame.setObjectName("ctrl_frame")
        self.Controls = QtWidgets.QLabel(self.ctrl_frame)
        self.Controls.setGeometry(QtCore.QRect(10, 10, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(16)
        self.Controls.setFont(font)
        self.Controls.setAlignment(QtCore.Qt.AlignCenter)
        self.Controls.setObjectName("Controls")
        self.SiteType = QtWidgets.QLabel(self.ctrl_frame)
        self.SiteType.setGeometry(QtCore.QRect(10, 60, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.SiteType.setFont(font)
        self.SiteType.setObjectName("SiteType")
        self.Output = QtWidgets.QLabel(self.ctrl_frame)
        self.Output.setGeometry(QtCore.QRect(10, 260, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.Output.setFont(font)
        self.Output.setObjectName("Output")
        self.layoutWidget = QtWidgets.QWidget(self.ctrl_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 320, 331, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Format = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.Format.setContentsMargins(0, 0, 0, 0)
        self.Format.setObjectName("Format")
        self.json = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.json.setFont(font)
        self.json.setObjectName("json")
        self.Format.addWidget(self.json)
        self.csv = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.csv.setFont(font)
        self.csv.setObjectName("csv")
        self.Format.addWidget(self.csv)
        self.fmt = QtWidgets.QLabel(self.ctrl_frame)
        self.fmt.setGeometry(QtCore.QRect(30, 290, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.fmt.setFont(font)
        self.fmt.setObjectName("fmt")
        self.layoutWidget_8 = QtWidgets.QWidget(self.ctrl_frame)
        self.layoutWidget_8.setGeometry(QtCore.QRect(30, 190, 331, 27))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.Tabletype = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.Tabletype.setContentsMargins(0, 0, 0, 0)
        self.Tabletype.setObjectName("Tabletype")
        self.stic = QtWidgets.QRadioButton(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.stic.setFont(font)
        self.stic.setObjectName("stic")
        self.Tabletype.addWidget(self.stic)
        self.dynamic = QtWidgets.QRadioButton(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.dynamic.setFont(font)
        self.dynamic.setObjectName("dynamic")
        self.Tabletype.addWidget(self.dynamic)
        self.TableType = QtWidgets.QLabel(self.ctrl_frame)
        self.TableType.setGeometry(QtCore.QRect(10, 160, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.TableType.setFont(font)
        self.TableType.setObjectName("TableType")
        self.pushButton = QtWidgets.QPushButton(self.ctrl_frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 800, 361, 25))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.ctrl_frame)
        self.widget.setGeometry(QtCore.QRect(30, 90, 331, 27))
        self.widget.setObjectName("widget")
        self.Iter = QtWidgets.QHBoxLayout(self.widget)
        self.Iter.setContentsMargins(0, 0, 0, 0)
        self.Iter.setObjectName("Iter")
        self.single = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.single.setFont(font)
        self.single.setObjectName("single")
        self.Iter.addWidget(self.single)
        self.complete = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.complete.setFont(font)
        self.complete.setObjectName("complete")
        self.Iter.addWidget(self.complete)
        self.gridLayout.addWidget(self.ctrl_frame, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 3, 1)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fetch.setText(_translate("Dialog", "Fetch"))
        self.URL.setPlaceholderText(_translate("Dialog", "Site URL"))
        self.Controls.setText(_translate("Dialog", "Controls"))
        self.SiteType.setText(_translate("Dialog", "Search for Table In:"))
        self.Output.setText(_translate("Dialog", "Output Options:"))
        self.json.setText(_translate("Dialog", "JSON"))
        self.csv.setText(_translate("Dialog", "CSV"))
        self.fmt.setText(_translate("Dialog", "Format"))
        self.stic.setToolTip(_translate("Dialog", "Select if table data does not change over time"))
        self.stic.setText(_translate("Dialog", "Static"))
        self.dynamic.setToolTip(_translate("Dialog", "Select if table data changes with time"))
        self.dynamic.setText(_translate("Dialog", "Dynamic"))
        self.TableType.setText(_translate("Dialog", "Table Type"))
        self.pushButton.setText(_translate("Dialog", "Confirm Entry"))
        self.single.setText(_translate("Dialog", "Single Page"))
        self.complete.setText(_translate("Dialog", "Whole Site"))
